language: node_js
node_js:
  - "12.16"
branches:
  only:
  - master
addons:
  apt:
    chrome: stable
before_script:
  - npm install -g @angular/cli
script:
  - ng test --watch false --browsers ChromeHeadless
