language: node_js
node_js:
  - "12.16"
branches:
  only:
  - master
addons:
  apt:
    chrome: stable
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
