language: node_js
node_js:
- '12.16'
branches:
  only:
  - master
addons:
  apt:
    chrome: stable
before_script:
- npm install -g @angular/cli
script:
- ng test --watch false --browsers ChromeHeadless
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: kuSnraS8IwE1x/liC6ZdxgMV4OuTbLDBrHXWXNLUlU2P4NGtBASeEQTUmkCHdyXaAa4PqFFIl9zzBT4tJt8uL2j6A5ElUE/i2XRL0UwFOMRVOm+FSAiuZ34JabFDHqyFQeteMc3i9sclCJe8biCBJ5XQMJlkz3HHVQz+QuxGnW0kWpu/Pwk7rcOckaHyqqR7mzOPGPwo+gaKw1YZH1b1MggskAzPqVoYDgboNblhtxGop3keBruIFgVAEVnWT6s0WUCKmVzesksS8S95peZOP8XSj3lQ9kYgfQlhMFYaYLVsy4DsQF/onbLDxQYwVksVkLIGA+yUVrmLDxn6ZHJOsUPXuSk3DWH1Yd+cE40piR4wsE8AC2QxLcEWgo7v5K88EtAHdJpAVccSJ9DUrwwFDRlKZ0UKPoO1/WXnYZLyyE1ymEAg6wznqvmN4P9m2aZntU3iFvGepJex2y/nxRTs9/9/G+BEBr9+lRBD8COtrnhxSXmW4dwzXS5zucnKhX7Dezlthw0aUDWnOtHUUt9nZyXNNkZpf/QrB53K1iB7jrxOQvDNoM9VeWch2DC7X1JTqaKvV+FU3Rut9+z7dGFJciLVavPLORbrcPj/afYu11xcuO6/x65KA9Gq09Qmz3mKWIxHgQviHvWryMfkN0hl0BbTrzT5bF5QUjjRvz8Uqlo=
env:
  global:
    secure: kuSnraS8IwE1x/liC6ZdxgMV4OuTbLDBrHXWXNLUlU2P4NGtBASeEQTUmkCHdyXaAa4PqFFIl9zzBT4tJt8uL2j6A5ElUE/i2XRL0UwFOMRVOm+FSAiuZ34JabFDHqyFQeteMc3i9sclCJe8biCBJ5XQMJlkz3HHVQz+QuxGnW0kWpu/Pwk7rcOckaHyqqR7mzOPGPwo+gaKw1YZH1b1MggskAzPqVoYDgboNblhtxGop3keBruIFgVAEVnWT6s0WUCKmVzesksS8S95peZOP8XSj3lQ9kYgfQlhMFYaYLVsy4DsQF/onbLDxQYwVksVkLIGA+yUVrmLDxn6ZHJOsUPXuSk3DWH1Yd+cE40piR4wsE8AC2QxLcEWgo7v5K88EtAHdJpAVccSJ9DUrwwFDRlKZ0UKPoO1/WXnYZLyyE1ymEAg6wznqvmN4P9m2aZntU3iFvGepJex2y/nxRTs9/9/G+BEBr9+lRBD8COtrnhxSXmW4dwzXS5zucnKhX7Dezlthw0aUDWnOtHUUt9nZyXNNkZpf/QrB53K1iB7jrxOQvDNoM9VeWch2DC7X1JTqaKvV+FU3Rut9+z7dGFJciLVavPLORbrcPj/afYu11xcuO6/x65KA9Gq09Qmz3mKWIxHgQviHvWryMfkN0hl0BbTrzT5bF5QUjjRvz8Uqlo=
