language: node_js
node_js:
  - "12.16"
branches:
  only:
    - master
addons:
  apt:
    chrome: stable
befor_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
